version: '3'

services:
  webscanner-foretend:
    build:
      context: ./webscanner-foretend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  webscanner-backend:
    build:
      context: ./webscanner-backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://damn:123000123@db:5432/scanner
    depends_on:
      - db
    ports:
      - "5000:5000"

  pikachu:
    build:
      context: ./pikachu
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: damn
      POSTGRES_PASSWORD: 123000123
      POSTGRES_DB: scanner
    ports:
      - "5432:5432"
networks:
  default:
